name: mental-health-predictor

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phq9_backend
    restart: unless-stopped
    ports:
      - "5050:5050"
    networks:
      - mh-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phq9_frontend
    restart: unless-stopped
    ports:
      - "3333:3333"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:5050
    networks:
      - mh-net

networks:
  mh-net:
    driver: bridge
